/* Demo dataset (local). */
window.TUTORS = [
  {
    id: 1,
    name: "Анна Смирнова",
    subjects: ["Математика", "Физика"],
    rating: 4.8,
    price: 1200,
    description: "7 лет опыта, подготовка к ОГЭ/ЕГЭ, объясняю простым языком.",
    education: "СурГУ, прикладная математика",
    experienceYears: 7,
  },
  {
    id: 2,
    name: "Дмитрий Кузнецов",
    subjects: ["Информатика", "Программирование"],
    rating: 4.6,
    price: 1500,
    description: "Алгоритмы, Python/JS, проекты. Подготовка к олимпиадам.",
    education: "СПбПУ, ИТ",
    experienceYears: 6,
  },
  {
    id: 3,
    name: "Екатерина Иванова",
    subjects: ["Английский язык"],
    rating: 4.9,
    price: 1700,
    description: "Разговорная практика и грамматика, уровень A1–C1.",
    education: "РГПУ, лингвистика",
    experienceYears: 9,
  },
  {
    id: 4,
    name: "Сергей Петров",
    subjects: ["Русский язык", "Литература"],
    rating: 4.5,
    price: 1100,
    description: "Сочинения, грамотность, подготовка к экзаменам.",
    education: "ТюмГУ, филология",
    experienceYears: 8,
  },
  {
    id: 5,
    name: "Мария Орлова",
    subjects: ["Химия", "Биология"],
    rating: 4.7,
    price: 1400,
    description: "Понятные схемы, практика задач, уверенность на экзамене.",
    education: "СибГМУ, биохимия",
    experienceYears: 5,
  },
  {
    id: 6,
    name: "Алексей Морозов",
    subjects: ["История", "Обществознание"],
    rating: 4.4,
    price: 1000,
    description: "Логика, карты, даты без зубрёжки, разбор критериев.",
    education: "УрФУ, история",
    experienceYears: 6,
  },
  {
    id: 7,
    name: "Ольга Соколова",
    subjects: ["Английский язык", "Немецкий язык"],
    rating: 4.3,
    price: 1600,
    description: "Коммуникативная методика, расширение словаря.",
    education: "МГЛУ, перевод",
    experienceYears: 4,
  },
  {
    id: 8,
    name: "Илья Фёдоров",
    subjects: ["Математика"],
    rating: 4.2,
    price: 900,
    description: "База + уверенное решение задач, спокойный темп.",
    education: "НГУ, математика",
    experienceYears: 3,
  },
  {
    id: 9,
    name: "Наталья Васильева",
    subjects: ["Физика", "Информатика"],
    rating: 4.1,
    price: 1300,
    description: "Физика с пониманием, практические примеры, задачи.",
    education: "МИФИ, физика",
    experienceYears: 5,
  },
  {
    id: 10,
    name: "Павел Андреев",
    subjects: ["География", "История"],
    rating: 4.0,
    price: 800,
    description: "Короткие конспекты, тренажёры, закрепление тем.",
    education: "ТГУ, география",
    experienceYears: 2,
  },
  {
    id: 11,
    name: "Вероника Белова",
    subjects: ["Математика", "Информатика", "Программирование"],
    rating: 4.9,
    price: 1900,
    description: "Системная подготовка, контроль прогресса, проекты.",
    education: "ИТМО, программная инженерия",
    experienceYears: 10,
  },
  {
    id: 12,
    name: "Роман Егоров",
    subjects: ["Русский язык"],
    rating: 3.9,
    price: 700,
    description: "Грамматика с нуля, разбор типичных ошибок.",
    education: "КФУ, филология",
    experienceYears: 1,
  },
  {
    id: 13,
    name: "Юлия Ким",
    subjects: ["Китайский язык", "Английский язык"],
    rating: 4.6,
    price: 2000,
    description: "Произношение, иероглифы, разговорная практика.",
    education: "ДВФУ, востоковедение",
    experienceYears: 6,
  },
  {
    id: 14,
    name: "Кирилл Никитин",
    subjects: ["Физика"],
    rating: 4.7,
    price: 1450,
    description: "Сильная теория + задачи, подготовка к ЕГЭ профиль.",
    education: "МФТИ, прикладная физика",
    experienceYears: 7,
  },
  {
    id: 15,
    name: "Светлана Тарасова",
    subjects: ["Биология"],
    rating: 4.3,
    price: 1250,
    description: "Систематизация материала, тесты, домашка с проверкой.",
    education: "СПбГУ, биология",
    experienceYears: 4,
  },
];

